### ISSUE TITLE
Hello.

### ISSUE THREAD

**Issue by wasdennnoch** [wasdennnoch/FastHub-collaborator-test#2]
```java
fancy code that is not code
```

**Comment by k0shk0sh** [comment]
yup, I can't close it or do anything with it. I will have to work this out tomorrow tho, as its 10:34PM overhere. again, Thank you very much.

**Comment by k0shk0sh** [comment]
alright this issue is fixed, you can delete this repo now :D.
thanks man.

**Comment by wasdennnoch** [comment]
No problem man.
